Raghad ahmed gad

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/user/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/user/anaconda3\\Libr

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print(len(arr))

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
zer=np.zeros(10)
zer[4]=1
print(zer)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
arr=[10,20,30,40,50]
arr_after=arr[::-1]

print(arr_after)

[50, 40, 30, 20, 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
mt=np.arange(9).reshape(3,3)
print(mt)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
arr=[1,2,0,0,4,0]
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
identety_mt=np.eye(3)
print(identety_mt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
arr=np.random.random((3,3,3))
arr

array([[[0.18581843, 0.658181  , 0.21357651],
        [0.57908433, 0.00755883, 0.96206198],
        [0.67834726, 0.49819245, 0.21668928]],

       [[0.81351014, 0.76882088, 0.00107523],
        [0.70446202, 0.14566363, 0.00797369],
        [0.39693551, 0.87609412, 0.97379516]],

       [[0.05827635, 0.09127593, 0.91989639],
        [0.46408132, 0.43508079, 0.37605253],
        [0.55254899, 0.12722744, 0.62789238]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
arr=np.random.rand(10,10)
print(arr)

mx=arr.max()
print("max value",mx)
mn=arr.min()
print("min value",mn)

[[0.27511737 0.30002923 0.70056478 0.49727883 0.97526795 0.98794644
  0.8065411  0.76290722 0.43188227 0.38092869]
 [0.07415167 0.09033199 0.95672503 0.17066491 0.33714151 0.74659273
  0.96628826 0.18729082 0.54770078 0.75844399]
 [0.69230198 0.57293457 0.0964878  0.73454861 0.10680145 0.18739834
  0.5890088  0.28410801 0.77747835 0.16780145]
 [0.95149325 0.02763368 0.80770141 0.83033623 0.73910944 0.53032771
  0.58139374 0.85045169 0.09085697 0.15279953]
 [0.8373155  0.12985788 0.82700322 0.96538313 0.98999956 0.90033196
  0.76389073 0.92981808 0.10529466 0.55841243]
 [0.84626051 0.2439965  0.78224361 0.62995978 0.86504045 0.04280464
  0.35811463 0.97992708 0.77757746 0.82141087]
 [0.97851655 0.1808972  0.24314702 0.34381355 0.50740107 0.96844826
  0.45769646 0.42389113 0.410406   0.7164247 ]
 [0.31808505 0.96164183 0.98945186 0.01949336 0.6475367  0.12815883
  0.51767301 0.00696867 0.89927072 0.54588606]
 [0.56362422 0.15914852 0.31751739 0.52481391 0.5267053  0.63014423
  0.84128222

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
arr=np.random.rand(30)
print(arr)
print("mean value",arr.mean())

[8.54867177e-01 5.46963419e-01 2.25423639e-01 2.43332524e-01
 6.58829772e-01 4.52236437e-01 8.30533630e-01 3.27416952e-01
 9.98671695e-01 5.89399849e-01 5.98644603e-01 1.58124681e-01
 7.50813598e-01 4.72597857e-01 8.78339137e-02 3.25764319e-01
 7.66058637e-01 3.49267813e-01 9.73494462e-01 8.49824786e-01
 2.04592235e-01 1.61297218e-02 8.78311994e-01 9.95305925e-01
 4.74652458e-01 8.39139954e-01 7.58637193e-04 7.88331975e-01
 4.52107347e-01 4.64266624e-01]
mean value 0.5391232212384012


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [35]:
arr=np.ones((10,10))
arr[1:-1,1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [36]:
arr=np.ones((10,10))


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
arr = np.diag([1,2,3,4],k=-1)
arr


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [48]:

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [52]:
arr=[[0,1],[1,0]]
arr_after=np.tile(arr,(4,4))
arr_after

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [53]:
print(np.random.randn(5,5))

[[-1.03949738 -1.10125651  1.7084397   0.44178947 -0.13673194]
 [ 0.24359454  0.9020438  -0.33011646 -1.87280037 -0.19748634]
 [-0.43288068 -0.70766876  1.0993769   0.67218359 -1.84892305]
 [-1.18894137 -1.15035226  0.70103638 -0.21827755 -2.49092107]
 [ 0.25440153  0.76200991 -0.72422505 -0.09527782 -0.40471615]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [54]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\user\AppData\Local\Temp\ipykernel_19812\2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [58]:
arr1=np.array([1,2,3])
arr2=np.array([2,5,8])
print(arr1.dot(arr2))


36


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [60]:
arr= np.arange(11)
arr[(3 < arr) & (arr <= 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [59]:
print(sum(range(5),-1))

from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [65]:
Z=np.array([1,2,3])
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [66]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\user\AppData\Local\Temp\ipykernel_19812\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_19812\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\user\AppData\Local\Temp\ipykernel_19812\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
arr=np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(arr)), arr))


[-3.  8. -3. -5. -2.  9. -1. -4.  6. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [68]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [69]:
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\user\AppData\Local\Temp\ipykernel_19812\2961820512.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [72]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [73]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [74]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [75]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 4. 5. 9. 9. 7. 8. 7. 2. 2.]
[2. 4. 5. 9. 9. 7. 8. 7. 2. 2.]
[2. 4. 5. 9. 9. 7. 8. 7. 2. 2.]
[2 4 5 9 9 7 8 7 2 2]
[2. 4. 5. 9. 9. 7. 8. 7. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [76]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [77]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [78]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [86]:
arr=np.random.rand(10)
arr.sort()
print(arr)

[0.13324428 0.22969378 0.39028445 0.44895063 0.52712791 0.65711084
 0.72508505 0.83222445 0.93905269 0.94352407]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [87]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [89]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [91]:
Z = np.zeros(10)
Z.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [92]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.92506631 0.90286345 0.40683046 0.83343995 0.77541138 0.18632492
 0.92600064 1.26561215 0.80865981 0.77336745]
[0.10130533 0.89803906 0.05891201 1.25060503 1.36868875 0.44477385
 1.29729589 0.75243763 1.30685744 0.52365065]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [100]:
arr=np.random.rand(10)
arr[arr.argmax()]=0
arr

array([0.72280803, 0.22553985, 0.51594634, 0.58877216, 0.57352606,
       0.        , 0.33755436, 0.05070637, 0.7997745 , 0.17834837])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [103]:
arr= np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [104]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [105]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [117]:
print(np.random.rand(10))


[0.28919817 0.23038135 0.71990982 0.9607596  0.77970498 0.26529247
 0.90228934 0.64116789 0.71766449 0.09848799]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [118]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

88


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [3]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\user\AppData\Local\Temp\ipykernel_26464\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [4]:
arr = np.arange(10, dtype=np.int32)
arr = arr.astype(np.float32, copy=False)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [7]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [8]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [9]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [12]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)



[[ 0.31743062  0.26775335  0.36630965 -0.35979158  0.18195087 -0.24480106
  -0.28000609 -0.1328484   0.13685175 -0.25284911]
 [-0.30550812 -0.32542298  0.52120443  0.1539779   0.20122827  0.33203004
  -0.40289668 -0.24786537 -0.08020863  0.15346114]
 [ 0.4125838   0.10982414 -0.29768766 -0.28524681  0.00785513 -0.22685334
   0.04503587 -0.26158045  0.29851074  0.19755859]
 [-0.29603752  0.22367739 -0.2630074  -0.39417205  0.35303953 -0.29914412
   0.10743785  0.35474832 -0.20146897  0.41492697]
 [-0.37131166 -0.17250572  0.28143309 -0.16446016  0.46141842 -0.13886126
  -0.0385501  -0.02516041 -0.33910852  0.50710632]]


#### 59. How to sort an array by the nth column? (★★☆)

In [13]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[8 0 9]
 [8 8 7]
 [8 2 2]]
[[8 0 9]
 [8 2 2]
 [8 8 7]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [18]:
T= np.random.randint(0,3,(3,10))
print(T)
print((~T.any(axis=0)).any())



[[2 1 1 0 0 2 2 0 0 0]
 [1 1 2 1 2 0 0 1 1 0]
 [0 1 2 2 1 1 1 2 2 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [33]:
ARR=np.random.randint((1,10,3))
print(ARR)
value=8
m = ARR.flat[np.abs(ARR - value).argmin()]
print(m)

[0 3 1]
3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [38]:
arr_1=np.arange(3).reshape(1,3)
arr_2=np.arange(3).reshape(3,1)
it = np.nditer([arr_1,arr_2,None])

for i,y,x in it:x[...]=i+y
print(it.operands[2])



[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [39]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [40]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 2. 4. 3. 4. 4. 3. 4. 2. 2.]
[3. 3. 7. 5. 7. 7. 5. 7. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [41]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [42]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [43]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 47 65 64]
 [51 58 64 60]
 [50 45 67 42]]
[[58 47 65 64]
 [51 58 64 60]
 [50 45 67 42]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [44]:

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4207451  0.64770122 0.42242204 0.36619914 0.59228503 0.37027404
 0.65702717 0.46092547 0.36776317 0.47472318]
0    0.420745
1    0.647701
2    0.422422
3    0.366199
4    0.592285
5    0.370274
6    0.657027
7    0.460925
8    0.367763
9    0.474723
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [45]:

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))

array([1.36858069, 0.67160241, 1.88646577, 0.818991  , 1.05565062])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [46]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [47]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [48]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [49]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  3) ( 0,  9) ( 1, 60) ( 1, 64) ( 3,  9) ( 6, 49) ( 6, 99) (10, 83)
 (10, 86) (17, 57) (17, 65) (25, 76) (25, 88) (40, 89) (40, 98) (47, 59)
 (47, 88) (49, 99) (57, 65) (59, 88) (60, 64) (64, 69) (64, 75) (69, 75)
 (74, 91) (74, 99) (76, 88) (83, 86) (89, 98) (91, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [50]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [51]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [52]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [53]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-2.14462575e-01,  1.43878461e-01,  8.21704844e-01, -5.03266051e-01,
        3.40292249e-01,  5.18094748e-01,  9.86465744e-01,  7.68607200e-01,
       -1.69491022e-04, -9.46752335e-01,  3.17426685e-01, -2.13115061e-01,
       -8.32306825e-01, -9.10437121e-01, -7.49723498e-01,  4.44911753e-01,
       -2.33866341e-02, -4.92717891e-01,  1.87017267e-01, -7.05931443e-01,
       -1.01178618e-01,  5.39431402e-01,  6.53210095e-01, -3.98980879e-01,
       -3.56294941e-01,  3.11783476e-01, -2.82058806e-01,  4.94932069e-01,
       -9.26789175e-01,  7.19333811e-02,  3.50859702e-01, -1.34234783e-01,
        6.29958330e-01, -6.85932374e-01, -7.84307874e-01,  4.11041958e-01,
       -7.55482194e-01, -7.65663441e-01,  4.84569919e-02,  1.34356426e-02,
       -3.59075066e-01,  9.90661032e-01, -2.33364807e-01,  5.02516933e-01,
       -8.90604553e-01, -6.99959936e-01,  5.60448873e-01,  7.66867986e-01,
       -1.50420708e-01, -8.14370859e-01,  9.76235876e-01,  2.42790923e-01,
       -8.10415602e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [54]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.24139412  9.43040865  3.15940365  0.90506392  6.70652588 11.97794262
  2.65977679  9.15452275  3.42539288 15.33529851]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [55]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.01514384  9.53331101  7.37767582  6.85723515  1.37808662  7.7262414
   0.85315723  0.89336596  0.23407353  3.57942669]
 [ 9.76359334  4.39537374  3.61267141  4.67668205  0.8669701   6.19590901
  11.32414592  6.59769873 11.82573747  9.60202219]
 [11.86165424  6.71575199 10.9947711   2.30709885  5.73209325  4.88472293
   3.48135761  5.96199357  0.34775332  2.72420696]
 [17.83117061  0.60325239 13.63469064  6.0918551  10.16481559  2.45751246
  11.85369876 13.08834028  3.29632901  2.2918645 ]
 [ 2.53529072  6.22300338  3.93040517  9.38847721  9.34383303  4.47760979
   2.4091952   7.0608239   8.70400427  3.86059677]
 [ 3.43369387  2.22246381  0.27423552  3.399365    4.1096168   0.44842722
   3.34729226  0.69654753  9.08553071  5.46003693]
 [ 4.4889087   2.15113473  0.71182106  0.32159301  4.07042905  3.92425207
   7.25478367  1.26997757 12.75792859  9.51786822]
 [ 9.85359332  3.43157176  4.15912972  4.02336147  1.19341333  5.23421009
  10.60372661  6.4586237  10.82452481  8.57165184]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [57]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [58]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [59]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [60]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 3 1]
   [3 3 3]
   [1 3 3]]

  [[3 1 0]
   [3 3 0]
   [3 3 2]]

  [[1 0 1]
   [3 0 3]
   [3 2 4]]

  [[0 1 4]
   [0 3 4]
   [2 4 2]]

  [[1 4 4]
   [3 4 2]
   [4 2 0]]

  [[4 4 4]
   [4 2 3]
   [2 0 0]]

  [[4 4 0]
   [2 3 2]
   [0 0 4]]

  [[4 0 4]
   [3 2 4]
   [0 4 1]]]


 [[[3 3 3]
   [1 3 3]
   [4 2 1]]

  [[3 3 0]
   [3 3 2]
   [2 1 0]]

  [[3 0 3]
   [3 2 4]
   [1 0 3]]

  [[0 3 4]
   [2 4 2]
   [0 3 1]]

  [[3 4 2]
   [4 2 0]
   [3 1 3]]

  [[4 2 3]
   [2 0 0]
   [1 3 1]]

  [[2 3 2]
   [0 0 4]
   [3 1 0]]

  [[3 2 4]
   [0 4 1]
   [1 0 0]]]


 [[[1 3 3]
   [4 2 1]
   [2 1 2]]

  [[3 3 2]
   [2 1 0]
   [1 2 1]]

  [[3 2 4]
   [1 0 3]
   [2 1 2]]

  [[2 4 2]
   [0 3 1]
   [1 2 2]]

  [[4 2 0]
   [3 1 3]
   [2 2 2]]

  [[2 0 0]
   [1 3 1]
   [2 2 4]]

  [[0 0 4]
   [3 1 0]
   [2 4 1]]

  [[0 4 1]
   [1 0 0]
   [4 1 0]]]


 [[[4 2 1]
   [2 1 2]
   [1 2 1]]

  [[2 1 0]
   [1 2 1]
   [2 1 0]]

  [[1 0 3]
   [2 1 2]
   [1 0 0]]

  [[0 3 1]
   [1 2 2]
   [0 0 1]]

  [[3 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [61]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  8  6 10  1]
 [ 8  2 10 10 11]
 [ 6 10  6 42  6]
 [10 10 42  6  5]
 [ 1 11  6  5  8]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [62]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [63]:

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [64]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 1 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [65]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [67]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [69]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [72]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [73]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[~(Z[:,0,None]==Z[:,1:]).all(axis=1)]
print(U)

[[0 3 1]
 [1 0 3]
 [1 2 4]
 [1 0 0]
 [3 4 2]
 [1 4 4]
 [4 3 3]
 [3 3 1]
 [4 3 4]
 [2 4 0]]
[[0 3 1]
 [1 0 3]
 [1 2 4]
 [1 0 0]
 [3 4 2]
 [1 4 4]
 [4 3 3]
 [3 3 1]
 [4 3 4]
 [2 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [74]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [75]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [76]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.10801387, 0.24465276, 0.1754071 , 0.19852745, 0.27501082,
        0.12405936, 0.22576146, 0.34421506, 0.27556928, 0.19624479],
       [0.0772544 , 0.17498217, 0.12545583, 0.14199212, 0.19669506,
        0.08873056, 0.16147061, 0.24619178, 0.19709449, 0.1403595 ],
       [0.10326223, 0.23389023, 0.16769076, 0.18979403, 0.26291281,
        0.11860186, 0.21582998, 0.32907268, 0.2634467 , 0.18761178],
       [0.06526758, 0.14783188, 0.10599007, 0.11996058, 0.16617579,
        0.0749631 , 0.13641678, 0.20799258, 0.16651325, 0.11858127],
       [0.07729232, 0.17506805, 0.12551741, 0.14206181, 0.1967916 ,
        0.08877411, 0.16154986, 0.24631261, 0.19719123, 0.14042839],
       [0.11049286, 0.25026769, 0.17943281, 0.20308378, 0.28132249,
        0.1269066 , 0.23094283, 0.35211501, 0.28189377, 0.20074873],
       [0.11927421, 0.27015755, 0.19369311, 0.21922373, 0.30368041,
        0.13699242, 0.24929686, 0.38009911, 0.30429709, 0.2167031 ],
       [0.05565633, 0.12606228, 0.0903820

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [77]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [78]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [79]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30252176  0.02833317]
